---

- hosts: all
  gather_facts: no
  roles:
    - role: common

- hosts: controller-nodes
  gather_facts: no
  roles:
   - role: dbserver
   - role: dbserver_population
   - role: rabbitserver

- hosts: all
  gather_facts: no
  roles:
    - role: openstackclient

- hosts: controller-nodes
  gather_facts: no
  roles:
    - role: keystoneserver
      
- hosts: controller-nodes
  gather_facts: no
  roles:
    - role: keystone_population

### Before Glance

# - hosts: storage-nodes
#   roles: 
#     - role: glanceserver


# - hosts: controller-nodes
#   roles:
#     - role: novaserver
#     - role: nova_init


# - hosts: compute-nodes
#   roles:
#     - role: novacompute


# - hosts: controller-nodes
#   roles:
#    - role: neutronserver

# ### Before Open vSwitch

# - hosts: network-nodes
#   roles:
#     - role: neutron-agents
#     - role: openvswitch

# - hosts: compute-nodes
#   roles:
#     - role: neutron-agents-compute

# - hosts: controller-nodes
#   roles:
#     - role: horizon

# - hosts: controller-nodes
#   roles:
#     - role: cinderserver

# - hosts: storage-nodes
#   roles:
#     - role: cindervolume

# - hosts: controller-nodes
#   roles:
#     - role: heatserver

# - hosts: controller-nodes
#   roles:
#     - role: restart-services


