- name: ensure keystone and apache2 packages are installed
  apt: name={{ item }}
  loop:
    - keystone
    - apache2
    - libapache2-mod-wsgi

- name: ensure keystone service is stopped and disabled
  service: name=keystone state=stopped enabled=no

- name: ensure keystone database connections is configured
  ini_file:
    path: /etc/keystone/keystone.conf
    section: database
    option: connection
    value: mysql+pymysql://keystone:{{ keystone_db_password }}@{{ controller_ip }}/keystone

- name: ensure keystone is configured to use fernet tokens
  ini_file:
    path: /etc/keystone/keystone.conf
    section: token
    option: provider
    value: fernet

- name: ensure keystone is configured to use template catalog
  ini_file:
    path: /etc/keystone/keystone.conf
    section: catalog
    option: template_file
    value: /etc/keystone/default_catalog.templates

- name: ensure keystone is configured to use template catalog
  ini_file:
    path: /etc/keystone/keystone.conf
    section: catalog
    option: driver
    value: templated

- name: ensure keystone template catalog is updated
  template:
    src: etc/keystone/default_catalog.templates
    dest: /etc/keystone/default_catalog.templates
    owner: keystone
    group: keystone
    mode: 0644
    
- name: ensure wsgi-keystone.conf is present
  template: >-
    src=etc/apache2/sites-available/wsgi-keystone.conf
    dest=/etc/apache2/sites-available/wsgi-keystone.conf
    owner=root
    group=root
    mode=0644
  notify: restart apache2

- name: ensure virtual host wsgi is enabled
  shell: /usr/sbin/a2ensite wsgi-keystone.conf
  notify: restart apache2
  
- name: ensure apache is enabled and restarted
  service: name=apache2 state=restarted enabled=yes
  
- name: DB sync for keystone
  shell: /usr/bin/keystone-manage db_sync

- name: Fernet keys initialization
  shell: /usr/bin/keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone && keystone-manage credential_setup --keystone-user keystone --keystone-group keystone


# # - name: bootstrap identity service
# #   shell: keystone-manage bootstrap --bootstrap-password {{ admin_pass }} --bootstrap-admin-url http://{{ controller_ip }}:35357/v3/ --bootstrap-internal-url http://{{ controller_ip }}:35357/v3/ --bootstrap-public-url http://{{ controller_ip }}:5000/v3/ --bootstrap-region-id {{ region }}

# - name: ensure sqlite keystone database is deleted
#   file: dest=/var/lib/keystone/keystone.db state=absent
