- name: Ensure gpg is installed
  apt:
    name: gpg
    state: latest
    
- name: Ensure sources.list file is properly defined
  template: >
    src=etc/apt/sources.list
    dest=/etc/apt/sources.list
    owner=root
    group=root
    mode=0644

- name: Ensure osbpo GPG key is added
  apt_key: url=http://osbpo.debian.net/osbpo/dists/pubkey.gpg state=present
    
# - name: Ensure apt-pinning is set properly (stable packages will be installed by default)
#   copy: >
#     src=etc/apt/preferences
#     dest=/etc/apt/preferences
#     owner=root
#     group=root
#     mode=0644
  
- name: Ensure system is updated
  apt: update_cache=yes upgrade=yes

- name: Ensure timezone is defined
  when: timezone is defined
  command: /usr/bin/timedatectl set-timezone {{ timezone }}
  tags: timezone

- name: Ensure ntp is enabled
  command: /usr/bin/timedatectl set-ntp true
  tags: ntp

- name: Ensure timesyncd is enabled
  service: name=systemd-timesyncd enabled=yes
  tags: ntp
  notify:
  - restart timesyncd
  
# - name: Ensure memcached is installed
#   apt: name={{ item }}
#   with_items:
#     - memcached
#     - python-memcache
    
# - name: Ensure /etc/hosts is properly defined
#   copy: >-
#     src=etc/hosts
#     dest=/etc/hosts
#     owner=root
#     group=root
#     mode=0644
