- name: restart neutron-services
  service: name={{ item }} state=restarted
  loop:
    - neutron-api
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
