- name: ensure python-openstackclient is installed
  apt: name=python3-openstackclient 

- name: ensure the rest of openstack clients are installed
  apt: name={{ item }}
  loop:
    - python3-troveclient
    - python3-manilaclient
    - python3-heatclient
