- name: set openstack-dashboard-apache to be activated
  shell: echo openstack-dashboard-apache horizon/activate_vhost boolean true |debconf-set-selections
  
- name: set openstack-dashboard-apache-ssl to be activated
  shell: echo openstack-dashboard-apache horizon/use_ssl boolean true |debconf-set-selections

- name: ensure default virtualhost is disabled
  command: a2dissite {{ item }}
  loop:
    - 000-default
    - default-ssl
  notify: restart web services
  
- name: ensure horizon packages are installed 
  apt: name={{ item }}
  loop:
    - openstack-dashboard-apache

- name: configure local_settings.py
  template:
    src: etc/openstack-dashboard/local_settings.py
    dest: /etc/openstack-dashboard/local_settings.py
    owner: root
    group: root
    mode: 0644
  notify: restart web services

- name: ensure openstack-dashboard-ssl virtualhost is enabled
  command: a2ensite {{ item }}
  loop:
    - openstack-dashboard-ssl
    - openstack-dashboard-ssl-redirect
  notify: restart web services
  
- name: ensure ssl, wsgi and rewrite modules are enabled
  apache2_module: name={{ item }} state=present
  loop:
    - wsgi
    - ssl
    - rewrite
  notify: restart web services

# # Horizon css isn't loaded 

# - name: ensure manage.py collectstatic is executed again
#   command: /usr/share/openstack-dashboard/manage.py collectstatic --noinput --clear 
#   notify: restart web services

# - name: ensure manage.py compress is executed again
#   command: /usr/share/openstack-dashboard/manage.py compress --force
#   notify: restart web services

# - name: ensure django secret key is deleted
#   file: >-
#     path=/var/lib/openstack-dashboard/secret-key/.secret_key_store
#     state=absent
